name: WarpCommand
version: 1.0.0B
api: [4.0.0, 5.0.0]
main: Raphael\Teleporte
author: Raphael S.
description: Um plugin de Warp por comando!
permissions:
  setwarp.setwarp:
    default: op
    description: Permissão para poder criar uma warp.
  warp.comando:
    default: true
    description: Permissão padrão comandos warps.
