name: WarpCommand
version: 1.3.0
api: [4.0.0, 5.0.0]
main: Raphael1S\WarpCommand\Main
author: Raphael1S
description: "A simple but powerful Warps plugin!"


permissions:
  warpcommand.setwarp:
    default: op
    description: Permission to create a warp using /setwarp.
    
  warpcommand.delwarp:
    default: op
    description: Permission to delete a warp using /delwarp.
    
  warpcommand.warps:
    default: op
    description: Permission to view warps using /warps.

  warpcommand.updatewarp:
    default: op
    description: Permission to update warps using /updatewarp.
